Repository CRED-CLUB/neopop-web, pull requests merged in 2022-07, with the labels that each got.

#14 fix: disabled inputRef in InputField story playground controls
  src/components/InputField/InputField.stories.mdx
Labels: bug

#26 bug: fixes #25 add cleanup in scoremeter
  src/components/Scoremeter/index.tsx
Labels: improvements

#24 docs: add key prop in the list
  src/components/Typography/Typography.stories.mdx
Labels: improvements

#13 chore: add workflows
  .github/workflows/lint.yml
  .prettierrc
  package.json
Labels: enhancement

#28 fix: code improvements and cleanup
  src/components/Toast/Toast.stories.mdx
  src/components/Toast/components/ToastPortal.tsx
Labels: enhancement

#30 docs: fix typo and add description
  src/components/Button/Button.stories.mdx
  src/components/InputField/InputField.stories.mdx
Labels: documentation

#23 chore: Remove nullish coalescing and optional chaining plugins
  babel.config.json
  package-lock.json
  package.json
Labels: enhancement

#8 chore: fix typo
  src/components/BottomSheet/components/BottomSheetControlled.tsx
  src/components/BottomSheet/styles.ts
Labels: enhancement
